### PR TITLE
Update cloudwatch.rb

### PR DESCRIPTION
**Pull request by CliveJL**
Update cloudwatch.rb for Logstash 5.0 Event API changes (https://www.elastic.co/guide/en/logstash/current/event-api.html)

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by CliveJL** [comment]
This is my first ever GitHub Pull Request, so please accept my apologies if it's a little rough...

**Comment by jrgns** [comment]
@CliveJL No worries, looking good! I'll try and get this merged this week.

**Comment by sebamontini** [comment]
hey @jrgns any updates on this PR? the plugin seems to break without this fix

**Comment by torian** [comment]
Got hit by the same bug. Tested the change and works 👍

**Comment by pablodo** [comment]
:raising_hand_man: also need this change!

**Comment by davidstelter** [comment]
The logstash 5.2 RPMs are out now, still with broken CloudWatch output. This could use some attention.

**Comment by CliveJL** [comment]
Hi @jrgns , is there anything else I need to do with this PR to get it expedited?

**Comment by sebamontini** [comment]
hey @ph @jsvd any chance of merging this? it's been broken for a long time now and the PR is't pretty simple itself, no conflict no nothing...whats stopping this?

**Comment by jsvd** [comment]
version https://rubygems.org/gems/logstash-output-cloudwatch/versions/3.0.4 has been published with this pr

**Comment by jsvd** [comment]
thank you for the PR @CliveJL, sorry for the long time to merge

**Pull request closed without merging**
