### PR TITLE
update to new event api

### PR DESCRIPTION
**Pull request by talevy**

### CODE REVIEW

**Comment by jrgns** [comment]
I'm assuming this is part of elastic/logstash#5227 ?

**Comment by talevy** [comment]
@jrgns it is indeed. We plan on sending out an announcement about these upcoming changes shortly

**Comment by suyograo** [comment]
LGTM

**Comment by jrgns** [comment]
Ok. Should we be concerned about it breaking compatibility? Will we be bumping the major version?

**Comment by talevy** [comment]
@jrgns. Yes, this new API is only compatible with >= 5.x version of Logstash, so all plugins must be updated with these changes in order to be compatible with the next release of Logstash. We have tried to do the work on most of the plugins in the `logstash-plugins` organization. We are also working on an announcement on what this will mean and how other plugin authors can update their own plugins to keep up to date.

does that sound OK? Please let me know if you have any other concerns

**Pull request merged**
